package org.chuck;

import java.io.File;
import org.chuck.audio.ChuckAudio;
import org.chuck.core.ChuckArray;
import org.chuck.core.ChuckType;
import org.chuck.core.ChuckVM;

/** Diagnostic tool to verify Sequencer audio output programmatically. */
public class SequencerDiagnostic {
  public static void main(String[] args) throws Exception {
    int srate = 44100;
    ChuckVM vm = new ChuckVM(srate, 2);
    // Headless audio for testing
    ChuckAudio audio = new ChuckAudio(vm, 512, 2, (float) srate);
    vm.setAudio(audio);
    audio.start();
    audio.setMasterGain(1.0f);

    // 1. Setup the shared array exactly like the IDE does
    ChuckArray pattern = new ChuckArray(ChuckType.ARRAY, 8 * 16);
    for (int i = 0; i < 128; i++) pattern.setInt(i, 0L);

    // Trigger a KICK on the first step
    pattern.setInt(0, 1L);
    vm.setGlobalObject("seq_pattern", pattern);

    // Per-track probability
    ChuckArray probs = new ChuckArray(ChuckType.ARRAY, 8);
    for (int i = 0; i < 8; i++) probs.setFloat(i, 1.0);
    vm.setGlobalObject("seq_probability", probs);

    // 2. The Sequencer Engine code
    String code =
        """
            SndBuf kit[8];
            "examples/data/kick.wav" => kit[0].read;
            kit[0] => dac;

            // Wait for sync
            125::ms => dur T;
            0 => int step;

            while(step < 1) {
                if (Machine.getGlobalObject("seq_pattern") $ int[] @=> int data[]) {
                    if (data[0] > 0) {
                        0 => kit[0].pos;
                        <<< "DIAGNOSTIC: Triggering Kick...", "" >>>;
                    }
                }
                1::samp => now; // tiny advance to trigger
                step++;
            }
            100::ms => now; // let it play
            """;

    System.out.println("--- Starting Diagnostic ---");
    int id = vm.run(code, "diag.ck");
    if (id <= 0) {
      System.err.println("FAILED TO COMPILE ENGINE");
      return;
    }

    // 3. Advance time and check for non-zero output
    boolean soundDetected = false;
    double maxPeak = 0;

    for (int i = 0; i < 2000; i++) {
      vm.advanceTime(10); // small steps
      float out = Math.abs(vm.getChannelLastOut(0));
      if (out > maxPeak) maxPeak = out;
      if (out > 0.001) {
        soundDetected = true;
      }
    }

    System.out.println("--- Results ---");
    System.out.println("Max Peak Detected: " + maxPeak);
    if (soundDetected) {
      System.out.println("SUCCESS: Sound is being generated by the VM!");
    } else {
      System.out.println("FAILURE: VM output is SILENT.");
      // Check if file exists
      File f = new File("examples/data/kick.wav");
      System.out.println("Kick sample exists: " + f.exists() + " (" + f.getAbsolutePath() + ")");
    }

    audio.stop();
    System.exit(0);
  }
}
